name: GeoIPTools
main: uk.org.whoami.geoip.GeoIPTools
version: 0.5.1 B:7
authors:
- whoami
- Fishrock123
dev-url: http://dev.bukkit.org/server-mods/geoiptools/
commands:
    geoupdate:
        description: Update the GeoIPDatabase files
        usage: /geoupdate
        permission: geoiptools
permissions:
    geoiptools.*:
        description: Gives access to all GeoIPTools commands
        children:
            geoiptools.geoupdate: true
    geoiptools.geoupdate:
        description: Updates the database
        default: op